CREATE DATABASE CERVEJARIA;

USE CERVEJARIA;

CREATE TABLE CLIENTES(
IDCLIENTE INT IDENTITY (1,1) NOT NULL,
NOME VARCHAR (100) NOT NULL,
CPF VARCHAR (14) NOT NULL,
PTSFIDELIDADE DECIMAL DEFAULT 0,
DATANASCIMENTO DATE NOT NULL,
CONSTRAINT PK_CLIENTES_ID PRIMARY KEY (IDCLIENTE)
)

CREATE TABLE PRODUTOS(
IDPRODUTO INT IDENTITY (1,1) NOT NULL,
DESCRICAO VARCHAR (50) NOT NULL,
PRECO DECIMAL(10,2) NOT NULL,
QTDESTOQUE INT NOT NULL,
DATAVALIDADE DATE NOT NULL,
ATIVO BIT DEFAULT 1,
CONSTRAINT PK_PRODUTOS_ID PRIMARY KEY (IDPRODUTO)
)

CREATE TABLE PEDIDOS(
IDPEDIDO INT IDENTITY (1,1) NOT NULL,
CPFCLIENTE VARCHAR (14),
PRODUTOID INT NOT NULL,
QTDPRODUTO INT NOT NULL,
DATAPEDIDO SMALLDATETIME NOT NULL,
VALORTOTAL DECIMAL(10,2) NOT NULL,
STATUSPEDIDO INT DEFAULT 0,
CONSTRAINT PK_PEDIDOS_ID PRIMARY KEY (IDPEDIDO),
CONSTRAINT FK_PRODUTOS_ID FOREIGN KEY (PRODUTOID) REFERENCES PRODUTOS (IDPRODUTO)
)
USE CERVEJARIA;
USE CERVEJARIA;
SELECT * from CLIENTES
USE CERVEJARIA;
SELECT * from PRODUTOS
USE CERVEJARIA;
SELECT * from PEDIDOS 

